#!/bin/bash

#
# github-javadoc.sh - A script to build the javadocs of a SciJava-based project.
#

# The following repositories are known to use this script:
#
#   bonej-org/bonej-javadoc
#   fiji/fiji-javadoc
#   imagej/imagej-javadoc
#   imglib/imglib2-javadoc
#   scifio/scifio-javadoc
#   scijava/java3d-javadoc
#   scijava/scijava-javadoc
#   slim-curve/slim-javadoc
#   uw-loci/loci-javadoc

# Wait for a launched background command to complete, emitting
# an occasional message to avoid long periods without output.
# Return the same exit code as the launched command.
keep_alive() {
	pid="$1"
	if [ "$pid" = "" ]
	then
		echo "[ERROR] No PID given"
		return
	fi
	i=0
	while kill -0 "$pid" 2>/dev/null; do
		i=$((i+1))
		m=$((i/60))
		s=$((i%60))
		test $s -eq 0 && echo "[$m minutes elapsed]"
		sleep 1
	done
	wait "$pid"
}

######################## TODO ########################
if [ "$TRAVIS_SECURE_ENV_VARS" = true \
	-a "$TRAVIS_PULL_REQUEST" = false \
	-a "$TRAVIS_BRANCH" = master ]
then
	project=$1
	openssl_key=$2
	openssl_iv=$3

	# Populate the settings.xml configuration.
	mkdir -p "$HOME/.m2"
	settingsFile="$HOME/.m2/settings.xml"
	customSettings=.github/settings.xml
	if [ -f "$customSettings" ]
	then
		cp "$customSettings" "$settingsFile"
	else
		# NB: Use maven.scijava.org as sole mirror if defined in <repositories>.
		# This hopefully avoids intermittent "ReasonPhrase:Forbidden" errors
		# when the Travis build pings Maven Central; see travis-ci/travis-ci#6593.
		test -f pom.xml && grep -A 2 '<repository>' pom.xml | grep -q 'maven.scijava.org' &&
			cat >"$settingsFile" <<EOL
<settings>
	<mirrors>
		<mirror>
			<id>scijava-mirror</id>
			<name>SciJava mirror</name>
			<url>https://maven.scijava.org/content/groups/public/</url>
			<mirrorOf>*</mirrorOf>
		</mirror>
	</mirrors>
</settings>
EOL
	fi

	# Emit some details useful for debugging.
	# NB: We run once with -q to suppress the download messages,
	# then again without it to emit the desired dependency tree.
	mvn -B -q dependency:tree &&
	mvn -B dependency:tree &&

	echo &&
	echo "== Generating javadoc ==" &&

	# Build the javadocs.
	(mvn -B -q -Pbuild-javadoc) &
	keep_alive $! &&
	test -d target/apidocs &&
	# Strip out date stamps, to avoid spurious changes being committed.
	sed -i'' -e '/\(<!-- Generated by javadoc \|<meta name="date" \)/d' $(find target/apidocs -name '*.html') &&

	echo &&
	echo "== Configuring environment ==" &&

	# Configure SSH. The file .github/javadoc.scijava.org.enc must contain
	# an encrypted private RSA key for communicating with the git remote.
	mkdir -p "$HOME/.ssh" &&
	openssl aes-256-cbc -K "$openssl_key" -iv "$openssl_iv" -in '.github/javadoc.scijava.org.enc' -out "$HOME/.ssh/id_rsa" -d &&
	chmod 400 "$HOME/.ssh/id_rsa" &&

	# Configure git settings.
	######################## TODO ########################
	git config --global user.email "travis@travis-ci.com" &&
	git config --global user.name "Travis CI" &&

	echo &&
	echo "== Updating javadoc.scijava.org repository ==" &&

	# Clone the javadoc.scijava.org repository.
	git clone --quiet --depth 1 git@github.com:scijava/javadoc.scijava.org > /dev/null &&

	# Update the relevant javadocs.
	cd javadoc.scijava.org &&
	rm -rf "$project" &&
	mv ../target/apidocs "$project" &&

	# Commit and push the changes.
	git add "$project" &&
	success=1

	test "$success" || exit 1

	######################## TODO ########################
	git commit -m "Update $project javadocs (Travis build $TRAVIS_BUILD_NUMBER)"
	git pull --rebase &&
	git push -q origin gh-pages > /dev/null || exit 2

	echo "Update complete."
else
	echo "Skipping non-canonical branch $TRAVIS_BRANCH"
fi
