# This is a GitHub action that runs the following Travis builds every time a push/commit event occurs.
#
#   travis-build.sh
#   travisify.sh
#   travis-javadoc.sh

name: CI

# Triggers the workflow on push for every branch
on: push

jobs:
  build:
    # This workflow runs on Windows machines
    runs-on: windows-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      
      # Set up the JDK version
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      # Build by running travis-build.sh
      - name: travis-build
        run: |
          echo Running travis-build.sh
          sh ./travis-build.sh
          echo Finished running travis-build.sh
          
      # Build by running travisify.sh
      - name: travisify
        run: |
          echo Running travisify.sh
          sh ./travisify.sh
          echo Finished running travisify.sh

      # Build by running travis-javadoc.sh
      - name: travis-javadoc
        run: |
          echo Running travis-javadoc.sh
          sh ./travis-javadoc.sh
          echo Finished running travis-javadoc.sh
